apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: imsapp
  name: ims-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imsapp
  template:
    metadata:
      labels:
        app: imsapp
    spec:
      containers:
      - name: ingenims
        image: mavavericks/ims
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
