apiVersion: v1
kind: Service
metadata:
  labels:
    app: imsapp
  name: ims-service
  namespace: default
spec:
  selector:
    app: imsapp
  ports:
  - port: 8001
    targetPort: 8080
    protocol: TCP
  type: NodePort
